### PR TITLE
Fix #16: nixosProfiles -> nixosHosts

### LINKED ISSUE #16: profiles
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/51cb739c9c9c2258bc70747eb7bc22975ae244bd/systemFlake.nix#L9

`nixosProfiles` do contain system profiles, in a sense, but more accurately they contain host configs.

This clashes with devos' usage of the term `profiles` which is reserved for a very special meaning:

- profiles cannot declare options, but only make use of them. (while anything that declares options are _modules_)
- this rule makes modules a lot more reusable among the community

With `fup` reserving the name, we might have a problem finding an alternative naming scheme. (and also it's somewhat established, already)

/cc @Pacman99

### PR DESCRIPTION
**Pull request by blaggacao**
nixosProfiles might conflict a little too much with downstream naming.

### CODE REVIEW

**Comment by blaggacao** [comment]
Merging this as an implementation of authorized https://github.com/gytis-ivaskevicius/flake-utils-plus/issues/16#issuecomment-814999215

**Comment by Pacman99** [comment]
I would have preferred discussing hosts vs nixosHosts first. That would help for #17 and doing a rename in one swoop would be better.

**Comment by Pacman99** [comment]
I think everything should be hosts. Its getting very confusing to juggle around two names that are extremely similar. I say just rename to hosts and use host/hosts everywhere in fup. Leave the name `profiles` reserved for the more standard nixpkgs definition, a system agnostic config set.

**Comment by blaggacao** [comment]
`profile` &rarr; `config`? &mdash; they are mostly the contents of a traditional `/etc/nixos/configuration.nix`?

**Comment by gytis-ivaskevicius** [comment]
fup definition of `profiles is basically a "computer configuration". Word `host` seems to work fine in this context

**Pull request merged**
