### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by gytis-ivaskevicius**

### CODE REVIEW

**Comment by chvp** [comment]
Maybe I'm missing something, but multiple hosts don't seem to work right now. `nix flake show` only shows one of my hosts.

**Comment by blaggacao** [comment]
@chvp I'm currently working on #24 to try to catch any such potential issue in time. Might you bother yo lend me a hand with the issues I have there (I'm not really experienced with NixOS configs)?

**Comment by gytis-ivaskevicius** [comment]
Bug: mapAttrs does not properly merge hosts.

Example of the issue:
`mapAttrs' (a: b: {name = "nixosConfiguration"; value = b;}) {test = {a=1;}; test2 = {b = 2;}; }` evaluates to ` {nixosConfiguration = { a = 1; }; }`.

**Comment by chvp** [comment]
Is using a patched nixpkgs for a nixos configuration supposed to work right now on this branch? I removed all references to `nixpkgs.*` from my config (which is what I think https://github.com/gytis-ivaskevicius/flake-utils-plus/pull/6/files#diff-cc0cc16eba6f7c27b5cd6b8178a1902579199af567a10b55955a3246dd8ed38eR106 is for), but the patches don't seem to be used.

**Comment by blaggacao** [comment]
> Is using a patched nixpkgs for a nixos configuration supposed to work right now on this branch

I can't speak with authority, but I somwhere read it's not properly working and the general opinion is we should just loby for upstream solution via: https://github.com/NixOS/nix/issues/3920

**Comment by chvp** [comment]
As I understood it in #4, the nix limitation meant that users have to choose between configuring the nixpkgs in their config or patches. That's what the snippet I linked seems to imply too, but it doesn't seem to work.

**Comment by chvp** [comment]
Ah, I get why it isn't working. The condition uses `options`, not `config`. `nixos` always defines the `nixpkgs` options, so `_module.args.pkgs = selectedNixpkgs` will never be configured.

**Comment by gytis-ivaskevicius** [comment]
Alright, finally I implemented some sort of quality gate and all the tests pass except 1 - darwin support. Can someone who has more experience with it take a look at it?

**Comment by chvp** [comment]
> Alright, finally I implemented some sort of quality gate and all the tests pass except 1 - darwin support. Can someone who has more experience with it take a look at it?

I'm pretty sure the failure is because nix-darwin's config evaluation (https://github.com/LnL7/nix-darwin/blob/master/eval-config.nix#L3-L7) does not expect a `system` argument but it is passed by FUP [here](https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/staging/systemFlake.nix#L92).

**Comment by blaggacao** [comment]
@gytis-ivaskevicius have you seen https://github.com/gytis-ivaskevicius/flake-utils-plus/pull/35? I'd really like to have access to those quality gates conveniently in my local env with correctly pinned nixpkgs: for example my nixpkgs-fmt was constantly formatting differently for this project and another project.

**Comment by gytis-ivaskevicius** [comment]
@chvp - yeah, I realize the issue, it is just that I am not sure what's the best way of fixing it :/ Maybe I'll add additional flake something along the lines of "noSystem = true;". We will see, I just hoped that somebody will think of something nice

@blaggacao - Yeah, I reviewed it. TL;DR: I'd rather avoid having to manually specify hashes, but if you guys are fine with it - its all good. 
Obviously issue exists due to version differences:
20.09 - nixpkgs-fmt v1.0.0
unstable - nixpkgs-fmt v1.2.0
 
Also, I'd love to merge this. It 77 commits ahead by now :D So if we could be extra careful with the changes we are doing for an upcoming couple of days - that would be great. The plan is to write up a changelog of some sort tomorrow. Also if you guys could double-check the examples section - that would be awesome as well

**Comment by Pacman99** [comment]
> @chvp - yeah, I realize the issue, it is just that I am not sure what's the best way of fixing it :/ Maybe I'll add additional flake something along the lines of "noSystem = true;". We will see, I just hoped that somebody will think of something nice

We can just expose a custom builder for darwin that would essentially just be this: 
`args: nix-darwin.lib.darwinSystem (builltins.removeAttrs [ "system' ]`
Another issue is darwin sets nixpkgs.system, so we have to change fup to set the system as a default.

**Comment by blaggacao** [comment]
I'm still slightly in favor of built-in builders. Its always nice if users can offload responsability to rhe library.

**Comment by gytis-ivaskevicius** [comment]
Fixed up last issues there are (as far as I know). Here is a changelog,  please look over at ping me if I missed anything:
```
- Fixed `nixpkgs.config.*` options populating to nixpkgs.
- Removed NIX_PATH autogeneration. https://github.com/gytis-ivaskevicius/flake-utils-plus/issues/5.
- Added a pretty sick repl. Currently supports NixOS systems. Current REPL implementation will likely change in the future.
- Enforced passing `inputs` to modules.
- Added custom system builders support. This allows implementing configurations for darwin or standalone home-manager and much, much more
- Added exporter `lib.exporter.overlaysFromChanelsExporter`
- Added builder `lib.builders.packagesFromOverlaysBuiderConstructer`
- Added patching support for modules and lib's

- Deprecated `nixosProfiles` option in favor of `hosts`
- Deprecated `defaultSystem` option in favor of `hostDefaults.system`.
- Deprecated `sharedModules` option in favor of `hostDefaults.modules`.
- Deprecated `sharedExtraArgs` option in favor of `hostDefaults.extraArgs`.
```
Also, some markdown file with all the options is required at this point. I Will add it tomorrow (tho probably I will not bother writing documentation for all of it, atleast for time being

**Comment by blaggacao** [comment]
> - Added exporter `lib.exporter.overlaysFromChanelsExporter`
- Added builder `lib.builders.packagesFromOverlaysBuiderConstructer`

let's not advertise them yet, we might need to overhaul them shortly.

**Comment by blaggacao** [comment]
not sure what's the matter here, but I locally get:
```
nix build .#nixosConfigurations.Morty.config.system.build.toplevel --dry-run
warning: Git tree '/home/blaggacao/ghq/github.com/gytis-ivaskevicius/flake-utils-plus' is dirty
error: cannot import '/nix/store/720h8dynwphs8s4nq9sim9sk9yvpgwxb-nixpkgs-patched-d235056', since path '/nix/store/a5hrydwdnk2rwnn7nndbzb3x8pj60d6v-nixpkgs-patched-d235056.drv' is not valid

       at /nix/store/vsdykxyaxs09bacrwdyvmdn7advmk66i-source/systemFlake.nix:165:38:

          164|       let
          165|         importChannel = name: value: import (patchChannel system value.input (value.patches or [ ])) {
             |                                      ^
          166|           inherit system;
(use '--show-trace' to show detailed location information)
```

**Comment by gytis-ivaskevicius** [comment]
Yeah, I just figured it out. It is failing due to the `--dry-run` option.  That's unfortunate, i guess we will need to fix the CI

**Comment by gytis-ivaskevicius** [comment]
## flake-utils-plus v1.1.0 released!
Lots of changes and improvements. This release ended up with 92 commits. Wow, that's a lot of commitment ;)
Massive thanks to flake-utils-plus contributors: @blaggacao, @Pacman99, and @chvp. 

Additions:
- Added a pretty sick repl. Currently supports NixOS systems. Current REPL implementation will likely change in the future.
- Added custom system builders support. This allows implementing configurations for darwin or standalone home-manager and much, much more.
- Added patching support for modules and lib's.

Fixes and improvements:
- Enforced passing `inputs` to modules.
- Fixed `nixpkgs.config.*` options populating to nixpkgs.
- Fixed merging between options like `packagesBuilder` and `packages.<system>`.
- Removed NIX_PATH autogeneration. https://github.com/gytis-ivaskevicius/flake-utils-plus/issues/5

Deprecations (These options will be removed in future releases):
- Deprecated `nixosProfiles` option in favor of `hosts`.
- Deprecated `defaultSystem` option in favor of `hostDefaults.system`.
- Deprecated `sharedModules` option in favor of `hostDefaults.modules`.
- Deprecated `sharedExtraArgs` option in favor of `hostDefaults.extraArgs`.

Other: 
- Some automated tests were set up to avoid breaking existing functionality.
- Improved documentation. (Still not great, but hey - that's NixOS ecosystem for you :D )

**Pull request merged**
