### PR TITLE
imp: make system output dynamic

### PR DESCRIPTION
**Pull request by blaggacao**
towards #79

### CODE REVIEW

**Comment by gytis-ivaskevicius** [comment]
Not suited for HM. Does not exactly solve anything since it lacks arguments that should be used to call builder :/

Maybe we could just code it dynamically so all `outputBuilder`  values would get passed to the main flake? Should not be terribly difficult

**Review by gytis-ivaskevicius — APPROVED** [review]
Looks great! But did you execute tests just to be sure?

**Comment by blaggacao** [comment]
> Looks great! But did you execute tests? (Just making sure)

I was doing that right now and this seems to trigger an infinite recursion. I'll report back as I learn more.

**Review by Pacman99 — APPROVED** [review]
nice! Yeah this works well

**Comment by blaggacao** [comment]
Both, repo tests as well as downstream tests succeeded with the latest fixup.

**Pull request merged**
