### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by gytis-ivaskevicius**

### CODE REVIEW

**Comment by gytis-ivaskevicius** [comment]
@blaggacao @Pacman99 Can you guys take a look at this, I'm not sure how it works https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/staging/examples/exporters/flake.nix#L36-L37

Also please go over the file structure and see if it looks good. I am still not quite happy with names, but they are acceptable I guess :D

**Comment by Pacman99** [comment]
> Can you guys take a look at this, I'm not sure how it works https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/staging/examples/exporters/flake.nix#L36-L37

I'm pretty sure with https://github.com/gytis-ivaskevicius/flake-utils-plus/commit/1a742047f3f7c97b22768ba7738ac5a01052099e fromOverlays should work fine. Your using it exactly right, it just needs `self.overlays` and fup will pass it `channels` since its a builder.

> Also please go over the file structure and see if it looks good. I am still not quite happy with names, but they are acceptable I guess :D

The file structure looks great and the flake.nix is very nice to read. Looking over staging, I don't have any complaints.

**Comment by gytis-ivaskevicius** [comment]
Alright then, it seems that it actually works. Not sure why it did not before? :thinking: Not reproducible :eyes:

Also, I just realized, I should have named the folder `lib` instead of `src` but that's very minor change :)

**Comment by Pacman99** [comment]
> Also, I just realized, I should have named the folder lib instead of src but that's very minor change :)

I like src, its a bit more common for code repositories. But I don't care either way.

**Review by fufexan — APPROVED** [review]

**Comment by gytis-ivaskevicius** [comment]
@blaggacao dude, what the hell? Who force pushes to staging and why and what are these edge cases. Please provide proper explanations

**Comment by gytis-ivaskevicius** [comment]
Reverted back to daab9cb03ad2343a8f3b4dbd75eddf9f78f80716 due to lack of explanation of everything

**Comment by blaggacao** [comment]
@gytis-ivaskevicius To be fair: "public" explanation would be more precise. :wink:

**Comment by gytis-ivaskevicius** [comment]
I wrote that comment before our call

**Comment by gytis-ivaskevicius** [comment]
Flake-utils-plus 1.2.0

Branching change:
From now on master serves as a development branch (previously staging was used for such purposes). Please use tags for stable releases of flake-utils-plus. In general, with the improvements in test harness, releases might happen more frequently. Sticking with a tagged release might offer better trade-offs going forward.
Please note, while 1.2.0 retains backwards compatibility, [1.2.1 is the same version with all backwards compatibility removed. ](https://i.redd.it/imcnk4p4cab71.png)

Improvements:
- Now overlays receive `srcs` option by default which represents Github repositories from inputs
- `channels.*.input` is no longer required. By default it gets autogenerated from `inputs`
- Added `nix.generateNixPathFromInputs` - Generates NIX_PATH from available inputs.
- Added `nix.linkInputs` - Symlinks inputs to /etc/nix/inputs.

Deprecations:
- Updated fup-repl implementation, now it is a package and can load flake references by path.
- Replaced xyzBuilder(s) with `outputsBuilder`.
- Replaced `saneFlakeDefaults` nixosModule with `nix.generateRegistryFromInputs` option (set it to `true` to enable it)

Implemented multiple exporters: (Please see examples on the project page!)
- `lib.exportModules` - Helper that builds attribute set of modules from paths.
- `lib.exportOverlays` - Helper that builds namespaced attribute set of overlays.
- `lib.exportPackages` - Helper that outputs packages depending on `meta.platforms`

**Pull request merged**
